apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-model-cache
  namespace: llm
spec:
  storageClassName: gp3-csi-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
