apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: granite-pvc
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    opendatahub.io/dashboard: "true"
  name: granite-pvc
  namespace: llm
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "10"
          memory: 20Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "6"
          memory: 16Gi
          nvidia.com/gpu: "1"
      runtime: granite-pvc
      storageUri: pvc://vllm-model-cache/granite-7b-lab
